"""Added chat_id to a path

Revision ID: c84b2e1c3141
Revises: fe13545e7427
Create Date: 2021-04-28 12:12:51.768799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84b2e1c3141'
down_revision = 'fe13545e7427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paths', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paths', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paths', type_='foreignkey')
    op.drop_column('paths', 'chat_id')
    # ### end Alembic commands ###
