#!/bin/bash
export GENI_DB_HOST='localhost'
export GENI_DB_NAME='genipersonalvisit'
export GENI_DB_USER='geniuser'
export GENI_DB_PASSWD='genipersonalvisit!user'
export GENI_CLIENT_SECRET='AATGHLSwFITr5E0jEkcrTKYday2bJHwu3BPkwtZO'
export GENI_CLIENT_ID='tUwZAls5rg6euVuiWKWibPzUCY0twJIuXc7qfdS3'
export GENI_MAILGUN_URL='https://api.mailgun.net/v3/mg.bslaw.net/messages'
export GENI_MAILGUN_API_KEY='key-3clih5seile6ply0co93rz3j7njxi1d6'
export GENI_FROM_ADDR='me@dragosroua.com'
#export GENI_REDIRECT_URL='http://dragosroua.com'
export GENI_REDIRECT_URL='http://localhost:5050/home'
export HOST='localhost'
export PORT='5050'
